--- !ruby/object:Container::Memento
cont_user_id: 22017
container_name: auth
ctype: service
persistent: true
conf_self_start: true
publisher_namespace: EnginesSystem
type_path: auth
last_error:
memory: '96'
shareable: false
hostname: auth
domain_name: engines.internal
kerberos: false
environments: []
volumes:
 auth_scripts:
  name: auth_static_store
  remotepath: "/home/auth/static/"
  localpath: "/opt/engines/etc/auth/"
  permissions: "rw"
 krbkdc_etc:
  name: krbkdc_etc
  remotepath: "/etc/krb5kdc"
  localpath: "/var/lib/engines/services/auth/etc/krb5kdc/"
  permissions: "rw"
 krbkdc_lib:
  name: krbkdc_lib
  remotepath: "/var/krb5/"
  localpath: "/var/lib/engines/services/auth/lib/krb5/"
  permissions: "rw"
 container_public:
  name: container_public
  remotepath: "/home/engines/etc/containers"
  localpath: "/opt/engines/run/public/services"
  permissions: ro
image: _Engines_System(flavor)/auth:_Engines_System(release)
port:
mapped_ports:
 ldap:
  name: kauth
  port: 88
  publicFacing: false
  external: 88
repo: na
last_result:
setState: running
conf_register_site: false
conf_register_dns: true
dependant_on:
- "dns"
- "syslog"
